name: Deploy to dev ekstern
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: dev
      decorator_environment: dev
      app_origin: "https://www.ekstern.dev.nav.no"
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
