
name: Test write variabel
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Octo Security Token Service
        uses: octo-sts/action@v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository_owner }}
          identity: readertoken
      - name: Update vars
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh variable set TEST_VARIABLE --env "dev" --body "$(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
